version: "3.9"

services:
  # MongoDB container
  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    # To check the mongo db data of the container, matching it with port 2717
    ports:
      - 2717:27017
    volumes:
      - mongodata:/data/db

  # Node Graphql Container
  api:
    build: .
    ports:
      - 3001:3001
    environment:
      APP_ENV: development
      PORT: 3001
      HOST: mongodb_container:27017
      USERNAME:
      PASSWORD:
      DATABASE: vehicles
      CONNECTION_URL:
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb

volumes:
  mongodata: {}
